workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - windows
    - docker
  script:
    - echo "Setting up Minikube Docker environment..."
    - minikube -p minikube docker-env --shell powershell | Invoke-Expression
    - echo "Building productcatalogservice..."
    - docker build -t productcatalogservice:latest ./src/productcatalogservice
    - echo "Building frontend..."
    - docker build -t frontend:latest ./src/frontend

deploy_image:
  stage: deploy
  tags:
    - windows
    - docker
  script:
    - echo "Deploying productcatalogservice..."
    - kubectl set image deployment/productcatalogservice server=productcatalogservice:latest
    - echo "Deploying frontend..."
    - kubectl set image deployment/frontend server=frontend:latest