workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - windows
    - docker
  script:
    - echo "Setting up Minikube Docker environment..."
    - minikube -p minikube docker-env --shell powershell | Invoke-Expression
    - echo "Building Docker image for productcatalogservice..."
    - docker build -t productcatalogservice:latest ./src/productcatalogservice

deploy_image:
  stage: deploy
  tags:
    - windows
    - docker
  script:
    - echo "Deploying to Minikube..."
    - kubectl set image deployment/productcatalogservice server=productcatalogservice:latest