name: Build and Deploy to Minikube

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Minikube Docker environment
        shell: powershell
        run: |
          minikube -p minikube docker-env --shell powershell | Invoke-Expression

      - name: Build Docker images
        shell: powershell
        run: |
          echo "Building productcatalogservice..."
          docker build -t productcatalogservice:latest ./src/productcatalogservice
          echo "Building frontend..."
          docker build -t frontend:latest ./src/frontend
          
      - name: Deploy to Minikube
        shell: powershell
        run: |
          echo "Deploying productcatalogservice..."
          kubectl set image deployment/productcatalogservice server=productcatalogservice:latest
          echo "Deploying frontend..."
          kubectl set image deployment/frontend server=frontend:latest